// Mock data for the application

export const mockCandidates = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    role: 'Full Stack Developer',
    status: 'completed',
    currentRound: 'DSA',
    overallScore: 87,
    aptitudeScore: 85,
    roleScore: 92,
    dsaScore: 84,
    appliedDate: '2026-03-15',
    completedDate: '2026-03-20',
    experience: 'Senior',
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'michael.chen@email.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    role: 'Frontend Developer',
    status: 'in-progress',
    currentRound: 'Role',
    overallScore: 72,
    aptitudeScore: 78,
    roleScore: 0,
    dsaScore: 0,
    appliedDate: '2026-03-28',
    completedDate: null,
    experience: 'Mid',
  },
  {
    id: '3',
    name: 'Emily Rodriguez',
    email: 'emily.r@email.com',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    role: 'Backend Developer',
    status: 'completed',
    currentRound: 'DSA',
    overallScore: 91,
    aptitudeScore: 90,
    roleScore: 94,
    dsaScore: 89,
    appliedDate: '2026-03-10',
    completedDate: '2026-03-18',
    experience: 'Senior',
  },
  {
    id: '4',
    name: 'James Wilson',
    email: 'j.wilson@email.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    role: 'DevOps Engineer',
    status: 'failed',
    currentRound: 'Aptitude',
    overallScore: 42,
    aptitudeScore: 42,
    roleScore: 0,
    dsaScore: 0,
    appliedDate: '2026-03-25',
    completedDate: '2026-03-25',
    experience: 'Junior',
  },
  {
    id: '5',
    name: 'Priya Sharma',
    email: 'priya.sharma@email.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
    role: 'Full Stack Developer',
    status: 'completed',
    currentRound: 'DSA',
    overallScore: 88,
    aptitudeScore: 86,
    roleScore: 91,
    dsaScore: 87,
    appliedDate: '2026-03-12',
    completedDate: '2026-03-19',
    experience: 'Mid',
  },
  {
    id: '6',
    name: 'David Kim',
    email: 'david.kim@email.com',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop',
    role: 'Data Scientist',
    status: 'pending',
    currentRound: 'Not Started',
    overallScore: 0,
    aptitudeScore: 0,
    roleScore: 0,
    dsaScore: 0,
    appliedDate: '2026-04-01',
    completedDate: null,
    experience: 'Senior',
  },
  {
    id: '7',
    name: 'Lisa Anderson',
    email: 'lisa.a@email.com',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=100&h=100&fit=crop',
    role: 'Frontend Developer',
    status: 'in-progress',
    currentRound: 'DSA',
    overallScore: 79,
    aptitudeScore: 82,
    roleScore: 85,
    dsaScore: 0,
    appliedDate: '2026-03-22',
    completedDate: null,
    experience: 'Mid',
  },
  {
    id: '8',
    name: 'Robert Taylor',
    email: 'r.taylor@email.com',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    role: 'Backend Developer',
    status: 'completed',
    currentRound: 'DSA',
    overallScore: 76,
    aptitudeScore: 74,
    roleScore: 78,
    dsaScore: 76,
    appliedDate: '2026-03-14',
    completedDate: '2026-03-21',
    experience: 'Junior',
  },
];

export const mockAssessments = [
  {
    id: '1',
    name: 'Full Stack Developer Assessment',
    type: 'Technical',
    duration: 120,
    totalQuestions: 50,
    passingScore: 70,
    rounds: ['Aptitude', 'Role', 'DSA'],
    status: 'active',
    createdDate: '2026-02-01',
  },
  {
    id: '2',
    name: 'Frontend Developer Assessment',
    type: 'Technical',
    duration: 90,
    totalQuestions: 40,
    passingScore: 65,
    rounds: ['Aptitude', 'Role', 'DSA'],
    status: 'active',
    createdDate: '2026-02-10',
  },
  {
    id: '3',
    name: 'Backend Developer Assessment',
    type: 'Technical',
    duration: 100,
    totalQuestions: 45,
    passingScore: 70,
    rounds: ['Aptitude', 'Role', 'DSA'],
    status: 'active',
    createdDate: '2026-02-15',
  },
];

export const mockResults = [
  { candidateId: '1', candidateName: 'Sarah Johnson', role: 'Full Stack Developer', score: 87, status: 'passed', date: '2026-03-20' },
  { candidateId: '3', candidateName: 'Emily Rodriguez', role: 'Backend Developer', score: 91, status: 'passed', date: '2026-03-18' },
  { candidateId: '5', candidateName: 'Priya Sharma', role: 'Full Stack Developer', score: 88, status: 'passed', date: '2026-03-19' },
  { candidateId: '8', candidateName: 'Robert Taylor', role: 'Backend Developer', score: 76, status: 'passed', date: '2026-03-21' },
  { candidateId: '4', candidateName: 'James Wilson', role: 'DevOps Engineer', score: 42, status: 'failed', date: '2026-03-25' },
];

export const mockQuestions = [
  {
    id: '1',
    text: 'What is the time complexity of binary search?',
    type: 'MCQ',
    difficulty: 'Easy',
    tags: ['DSA', 'Algorithms'],
    category: 'DSA',
    options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
    correctAnswer: 'O(log n)',
  },
  {
    id: '2',
    text: 'Explain the difference between var, let, and const in JavaScript.',
    type: 'Subjective',
    difficulty: 'Medium',
    tags: ['JavaScript', 'Frontend'],
    category: 'Role',
  },
  {
    id: '3',
    text: 'Which HTTP method is used to update a resource?',
    type: 'MCQ',
    difficulty: 'Easy',
    tags: ['Backend', 'HTTP'],
    category: 'Role',
    options: ['GET', 'POST', 'PUT', 'DELETE'],
    correctAnswer: 'PUT',
  },
  {
    id: '4',
    text: 'What is the output of: console.log(typeof null)?',
    type: 'MCQ',
    difficulty: 'Medium',
    tags: ['JavaScript', 'Aptitude'],
    category: 'Aptitude',
    options: ['null', 'undefined', 'object', 'string'],
    correctAnswer: 'object',
  },
  {
    id: '5',
    text: 'Implement a function to reverse a linked list.',
    type: 'Coding',
    difficulty: 'Hard',
    tags: ['DSA', 'Linked List'],
    category: 'DSA',
  },
];

export const mockPrompts = [
  {
    id: '1',
    name: 'JavaScript Question Generator',
    description: 'Generates JavaScript technical questions',
    template: 'Generate {count} {difficulty} level JavaScript questions focusing on {topics}',
    category: 'Frontend',
    version: '2.1',
    lastUpdated: '2026-03-15',
  },
  {
    id: '2',
    name: 'DSA Problem Generator',
    description: 'Creates data structure and algorithm problems',
    template: 'Create {count} {difficulty} DSA problems on {topics} with test cases',
    category: 'DSA',
    version: '1.8',
    lastUpdated: '2026-03-10',
  },
  {
    id: '3',
    name: 'System Design Evaluator',
    description: 'Evaluates system design answers',
    template: 'Evaluate the system design answer for scalability, reliability, and best practices',
    category: 'System Design',
    version: '1.5',
    lastUpdated: '2026-03-01',
  },
];

export const mockRoles = [
  {
    id: '1',
    name: 'Full Stack Developer',
    description: 'Develops both frontend and backend applications',
    skills: ['React', 'Node.js', 'JavaScript', 'MongoDB', 'Express', 'TypeScript', 'REST API', 'Git'],
    experienceLevel: 'Senior',
    candidateCount: 45,
    skillCategories: {
      frontend: ['React', 'JavaScript', 'TypeScript'],
      backend: ['Node.js', 'Express', 'MongoDB'],
      tools: ['Git', 'REST API'],
    },
  },
  {
    id: '2',
    name: 'Frontend Developer',
    description: 'Specializes in user interface development',
    skills: ['React', 'JavaScript', 'HTML', 'CSS', 'Tailwind', 'TypeScript', 'Redux', 'Webpack'],
    experienceLevel: 'Mid',
    candidateCount: 32,
    skillCategories: {
      frontend: ['React', 'JavaScript', 'HTML', 'CSS', 'Tailwind', 'TypeScript', 'Redux'],
      tools: ['Webpack'],
    },
  },
  {
    id: '3',
    name: 'Backend Developer',
    description: 'Focuses on server-side application logic',
    skills: ['Node.js', 'Python', 'MongoDB', 'PostgreSQL', 'Redis', 'Docker', 'Microservices', 'AWS'],
    experienceLevel: 'Senior',
    candidateCount: 28,
    skillCategories: {
      backend: ['Node.js', 'Python', 'MongoDB', 'PostgreSQL', 'Redis', 'Microservices'],
      tools: ['Docker', 'AWS'],
    },
  },
  {
    id: '4',
    name: 'DevOps Engineer',
    description: 'Manages deployment and infrastructure',
    skills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD', 'Jenkins', 'Terraform', 'Linux', 'Monitoring'],
    experienceLevel: 'Mid',
    candidateCount: 18,
    skillCategories: {
      devops: ['Docker', 'Kubernetes', 'CI/CD', 'Jenkins', 'Terraform'],
      cloud: ['AWS'],
      os: ['Linux', 'Monitoring'],
    },
  },
  {
    id: '5',
    name: 'Data Scientist',
    description: 'Analyzes and interprets complex data',
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'Pandas', 'SQL', 'Statistics', 'Data Visualization', 'R'],
    experienceLevel: 'Senior',
    candidateCount: 15,
    skillCategories: {
      programming: ['Python', 'R', 'SQL'],
      ml: ['Machine Learning', 'TensorFlow', 'Pandas'],
      analytics: ['Statistics', 'Data Visualization'],
    },
  },
];

export const mockDashboardStats = {
  totalCandidates: 248,
  activeTests: 42,
  passRate: 68,
  avgScore: 76.5,
};

export const mockPerformanceData = [
  { month: 'Jan', candidates: 45, passed: 30, failed: 15 },
  { month: 'Feb', candidates: 52, passed: 38, failed: 14 },
  { month: 'Mar', candidates: 67, passed: 48, failed: 19 },
  { month: 'Apr', candidates: 84, passed: 58, failed: 26 },
];

export const mockRoundPerformance = [
  { round: 'Aptitude', avgScore: 78, participants: 248 },
  { round: 'Role', avgScore: 82, participants: 186 },
  { round: 'DSA', avgScore: 71, participants: 142 },
];

export const mockActivityFeed = [
  { id: '1', type: 'candidate', message: 'Sarah Johnson completed Full Stack assessment', time: '5 min ago', icon: 'user' },
  { id: '2', type: 'assessment', message: 'New assessment created: Mobile Developer Test', time: '23 min ago', icon: 'file' },
  { id: '3', type: 'result', message: 'Emily Rodriguez scored 91% in Backend test', time: '1 hour ago', icon: 'trophy' },
  { id: '4', type: 'candidate', message: '3 new candidates registered', time: '2 hours ago', icon: 'users' },
  { id: '5', type: 'system', message: 'Question bank updated with 15 new problems', time: '3 hours ago', icon: 'database' },
];
